### ISSUE TITLE
`text ` argument to `lint` function does not work

### ISSUE THREAD

**Issue by flodel** [halpo/lint#11]
I suppose the `text` argument to the `lint` function is for testing things like:

lint(text = "a=1+1")

I get

Error in inherits(.data, "split") : object 'files' not found

Quick look at the code for `lint` and it seems that the `file` variable defined as `file <- textConnection(text)` should be named `files`.

**Comment by flodel** [comment]
Any chance this will make it to CRAN soon? It seems you have fixed quite a few bugs here since the last release. Thank you.

**Comment by halpo** [comment]
The next version of Lint will be with R Version 3.0 due to the changes in
core R and the end of support for the parser package.

On Thu, Jan 17, 2013 at 7:48 AM, flodel notifications@github.com wrote:

> Any chance this will make it to CRAN soon? It seems you have fixed quite a
> few bugs here since the last release. Thank you.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/halpo/lint/issues/11#issuecomment-12370750.

## 

Andrew
May the Open Source be with you.
