### ISSUE TITLE
unexpected file content requirements

### ISSUE THREAD

**Issue by flodel** [halpo/lint#12]
I can't put a finger on them, but there seems to be minimum file content requirements (other than syntactically valid R code) for the function `lint` to work fine.

For example, `lint` dies if provided an empty file, or a file with the following contents:

a <- "HELLO"
mysum <- sum
z <- 1:12

Here is the error message I am seeing:

> lint(file = "/tmp/Rtmpc5W4Xl/file4c7f408cd504")
> Lint checking: /tmp/Rtmpc5W4Xl/file4c7f408cd504
> Error in `[.data.frame`(ldply(parse.data, parse2find), names(empty.find)) :
>   undefined columns selected
> 15: lint(file = "/tmp/Rtmpc5W4Xl/file4c7f408cd504")
> 14: llply(files, lint_file, style = style)
> 13: structure(lapply(pieces, .fun, ...), dim = dim(pieces))
> 12: lapply(pieces, .fun, ...)
> 11: FUN(X[[1L]], ...)
> 10: llply(style, dispatch_test, file = file, parse.data = parse.data,
>         lines = lines)
> 9: structure(lapply(pieces, .fun, ...), dim = dim(pieces))
> 8: lapply(pieces, .fun, ...)
> 7: FUN(X[[3L]], ...)
> 6: find_region(exclude.region, file = file, lines = lines, parse.data = parse.data)
> 5: fun.region[[i]](file = file, lines = lines, parse.data = parse.data)
> 4: parse2find(call.args)
> 3: ldply(parse.data, parse2find)[names(empty.find)]
> 2: `[.data.frame`(ldply(parse.data, parse2find), names(empty.find))
> 1: stop("undefined columns selected")

**Comment by halpo** [comment]
Fixed with issue #11.  Not a length requirement, but an unrelated bug for improperly handled empty data frames in the region finder functions.  That bug has already been fixed.
