### ISSUE TITLE
Errors when calling from command line

### ISSUE THREAD

**Issue by cameronbracken** [halpo/lint#17]
I am attempting to write a wrapper script to call lint on an R code file and am running into and error when I call things from the command line using Rscript, while things work in the R console. See the example script in this gist:

https://gist.github.com/cameronbracken/6176642

on the command line I get:

```
$ ./Rlint.R lint_test.R 
Lint checking: lint_test.R
Error in valid_find(result) : could not find function "is"
Calls: lint ... FUN -> do.call -> <Anonymous> -> stopifnot -> valid_find
Execution halted
```

while in the R interpreter I get:

```
> lint('lint_test.R')
Lint checking: lint_test.R
Lint: Equal sign assignments: found on lines 1
Lint: Assignments are not allowed to be nested in function calls.: found on lines 1
```

P.S. that second lint comment in the R interpreter may be a separate issue

**Comment by tyner** [comment]
Try loading the 'methods' package first; it is not loaded by default in script mode.

**Comment by cameronbracken** [comment]
That did it. Looks like methods was added as an import on github but the change hasn't made it to CRAN yet.
