### ISSUE TITLE
removed from CRAN?

### ISSUE THREAD

**Issue by tyner** [halpo/lint#23]
https://cran.r-project.org/web/packages/lint/index.html says:

> Package ‘lint’ was removed from the CRAN repository.
> 
> Formerly available versions can be obtained from the archive. 
> 
> Archived on 2016-08-23 as requested by the maintainer andrew.redd@hsc.utah.edu. 

If this package is no longer maintained, is there a recommended replacement?

Thanks

**Comment by halpo** [comment]
Yes lint was removed from CRAN at my request.  Jim Hester recreated it in the [lintr](cran.r-project.org/package=lintr) package.  The new package has the backing of Rstudio and so will have more support than I can give lint.  The other functionality of lint that I had been working on will be made redundant with my work on the R Documentation Task Force.
